### ISSUE TITLE
Exit code 0 when tests fail

### ISSUE THREAD

**Issue by ShaunParsons** [nordcloud/serverless-mocha-plugin#104]
When we get a test failure from a test file, it doesn't correctly exit the process with an error code of 0.

**Comment by c0d3d** [comment]
See #99 

My fork has it on master, so you can pull from there in the interim if you need.

**Comment by ShaunParsons** [comment]
@c0d3d we're currently using this: https://github.com/nordcloud/serverless-mocha-plugin/pull/103 which includes a non zero exit code when a single test fails as well.

**Comment by ShaunParsons** [comment]
@KariHe has this been closed because its been resolved?
