### ISSUE TITLE
Is this the end?

### ISSUE THREAD

**Issue by Enase** [nordcloud/serverless-mocha-plugin#113]
Hello @mpuittinen

I noticed as per your GitHub contribution chart that you are not too much active since the end of H1/2018. I'd like to know what is the plan with this repository. Are you planning to come back and address the issues here? Are you seeking for contributions? Or should we consider this repository archived?

Thank you in advance.

**Comment by mpuittinen** [comment]
Hi @Enase 
I'm still maintaining this, mainly incorporating PRs submitted by others. i.e. the repo is not dead even though it is not actively developed further by myself.
