### ISSUE TITLE
startOffline.sh not working with newer versions of serverless offline

### ISSUE THREAD

**Issue by 0xkalle** [nordcloud/serverless-mocha-plugin#121]
I discovered, that the bash script to start serverless offline in the background do not work anymore. This is because the output of newer serverless offline versions do not include the line `Offline listening` anymore.

But the current script is searching for it within the "while"-line:

```
TMPFILE=/var/tmp/offline$$.log
if [ -f .offline.pid ]; then
    echo "Found file .offline.pid. Not starting."
    exit 1
fi

serverless offline 2>1 > $TMPFILE &
PID=$!
echo $PID > .offline.pid

while ! grep "Offline listening" $TMPFILE
do sleep 1; done

rm $TMPFILE
```

Maybe a note should be added to the readme say that this line needs to be adjusted. For serverless 6 (currently in alpha) "server ready" works well.

If you want I can also prepare a super tiny PR, but I guess somebody can just add a line on one of the next PRs. :) 

Best Regards,
Kalle

**Comment by KariHe** [comment]
@0xkalle if you could provide PR, it would help a lot as we currently don't have much time for maintaining these plugins. We are planning to release latest updates soon.

**Comment by 0xkalle** [comment]
#123 is open :)
