### ISSUE TITLE
Is it planned to release v1.12.0 also on npmjs?

### ISSUE THREAD

**Issue by agenthala** [nordcloud/serverless-mocha-plugin#125]
In v1.12.0 you made a fix in the test runner to enable also typescript tests. This feature would be nice to install it also over npm: https://www.npmjs.com/package/serverless-mocha-plugin

**Comment by garethmcc** [comment]
Please can we release the support for 1.12 to npm as well

**Comment by KariHe** [comment]
Duplicate of #127
