### ISSUE TITLE
Errors are not being caught what leads to timeouts

### ISSUE THREAD

**Issue by rafaljanicki** [nordcloud/serverless-mocha-plugin#33]
Hello,

When running async tests (= all which are related to sls) and when an assertion fails, the test is doing timeout instead of reporting the error directly. In order to catch the error, we'd have to do try-catch block around every callback.

Do you have any other solution for this? Shouldn't it be caught by the plugin or lambdaWrapper?

**Comment by mpuittinen** [comment]
This would be something that need to be implemented in lambda-wrapper. It seems that it already has a try-catch mechanism but the exception is thrown, we could change it so that. Filed issue https://github.com/SC5/lambda-wrapper/issues/12 
Let's continue the discussion there (closing this one).

**Comment by mpuittinen** [comment]
Upgraded lambda-wrapper to return errors from within modules but these still need to be handled in the tests somehow.
