### ISSUE TITLE
Pass context object to lamdba wrapper

### ISSUE THREAD

**Issue by leeeomaaax** [nordcloud/serverless-mocha-plugin#46]
Hi there! Is it possible to pass the context object to my lambda function?

I'd like to test the Cognito User Pool Identity but API Gateway passes it in the context object.

Thanks!

**Comment by laardee** [comment]
@leeeomaaax,  it seems that the [Lambda wrapper](https://github.com/SC5/lambda-wrapper) cannot handle `context` correctly. I'll try to fix that soon.

**Comment by leeeomaaax** [comment]
@laardee , Thanks! 

I ended up finding out that Cognito User Pool Identity is actually passed inside the event object at: 
event.requestContext.authorizer.claims.sub
