### ISSUE TITLE
callback should be optional

### ISSUE THREAD

**Issue by brian-traceme** [nordcloud/serverless-mocha-plugin#64]
In the AWS Lambda docs, calling the callback function is optional, but I find my serverless-mocha-plugin tests don't work unless I call the callback function. Could you please make it optional to match up with AWS?

I was trying to test a lambda that reacts to s3 events, having no need to return anything to the caller.

http://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-handler.html

"callback – You can use the optional callback to return information to the caller, otherwise return value is null."

**Comment by mpuittinen** [comment]
@brian-traceme What version of the plugin are you using? I tried the following on 1.5.1 (with serverless 1.20.2):
* Created new sls service with sls install -u https://github.com/SC5/sc5-serverless-boilerplate -n mocha-tests
* (install packages etc...)
* Created a new function with sls create function -f testFunction --handler testFunction.handler
* Modified testFunction.js : changed callback(null, response) to context.succeed(response)
* Added a console.log to test/testFunction.js (just to verify that the response is passed)
* Run sls invoke test
=> Tests are run as expected

**Comment by jplock** [comment]
Possibly fixed by https://github.com/nordcloud/serverless-mocha-plugin/commit/693a09d681aa80759d8c6dc57ded7fbcd2bda3a8 ?
