### ISSUE TITLE
Missing required key 'FunctionName' in params

### ISSUE THREAD

**Issue by bryanowen7** [nordcloud/serverless-mocha-plugin#82]
When I try to run my tests I get this weird error: https://pastebin.com/hUqGW1Bz

Using AWS.
Runtime: Node 6.10
Testing with: Node 8.9
Serverless version: 1.26.0

The function and the test files are literally the default generated ones...

**Comment by bryanowen7** [comment]
My fault, fixed.

**Comment by nenti** [comment]
How did you solve it?

**Comment by bryanowen7** [comment]
quite frankly I don't remember, sorry
