### ISSUE TITLE
Publish updated version

### ISSUE THREAD

**Issue by dhm116** [nordcloud/serverless-mocha-plugin#85]
I was just curious if it would be possible for you to update the version in `package.json` and publish a new release to `npm` at some point in the near future? It appears `1.8.0` was updated about [a month ago](https://github.com/nordcloud/serverless-mocha-plugin/commit/ae5b2fefc0ce40d002713401903b2e020ef929b1) and, although the dependencies had been updated, the version has not been.

If you're waiting for more changes before cutting a release, that's fine - would you happen to know when you would be planning on creating that next release if that is the case?

Thanks so much!

**Comment by mpuittinen** [comment]
Released serverless-mocha-plugin 1.8.1 with all the latest changes.

-Mikael
