### ISSUE TITLE
Support the `.test.js` naming convention

### ISSUE THREAD

**Issue by dhm116** [nordcloud/serverless-mocha-plugin#89]
We've noticed that if you happen to name your tests in the `functionName.test.js` style, as opposed to the `functionName.js` style, only the global env vars will be defined when you run the tests - none of the function-specific env vars will be set. This is caused by [this line in particular (utils.js#L45)](https://github.com/nordcloud/serverless-mocha-plugin/blob/master/utils.js#L45).

Is it possible to fix this with something as simple as
```javascript
const base = path.basename(val).replace(/(?:\.test)?\.js$/, '');
```
or is something more complex required?

**Comment by KariHe** [comment]
#122
