### ISSUE TITLE
plugin not found

### ISSUE THREAD

**Issue by azarboon** [nordcloud/serverless-mocha-plugin#90]
Hi,

I want to try serverless-mocha-plugin, but somehow I cant't make it run. i followed your instruction, that is:

`npm install --save-dev serverless-mocha-plugin`

and add it to plugins
```
plugins:
  - serverless-mocha-plugin
```

My serverless erison is 1.27.3. And I always get this error:

> Serverless plugin "serverless-mocha-plugin" not found. Make sure it's installed and listed in the "plugins" section of your serverless config file.

I'm not using any bundler such as webpack. Can you tell me what could be the root cause?

**Comment by azarboon** [comment]
Just tried to troubleshoot it and found that, when I run `npm i serverless-mocha-plugin`, even though it returns following:

> npm WARN test-npm@1.0.0 No description
> npm WARN test-npm@1.0.0 No repository field.
> 
> audited 78 packages in 1.516s
> found 0 vulnerabilities

However, it doesn't really install the library so I can't find bin files of this lib in node_modules. I tried it with npm 6 and npm 5, but problem persists. I don't have this problem with other packages.

**Comment by mpuittinen** [comment]
Hi! Which node version are you using? What OS are you running on? Tried with the latest serverless version the following:
> sls create -t aws-nodejs -p test -n test
> cd test/
> npm install --save-dev serverless-mocha-plugin
> sls create function -f testFunction --handler testFunc.handler

which succeeds as expected

**Comment by KariHe** [comment]
Closing as no response received.
