### ISSUE TITLE
After a faile test, it is shows as passing

### ISSUE THREAD

**Issue by jiffify** [nordcloud/serverless-mocha-plugin#93]
I'm using 1.9.0
I'm using below command to invoke the test. 
sls invoke test --exit -f create

Although, I'm failing one of the assertions, but reported shows me as passing.

  
error { AssertionError: expected 45 to deeply equal 5
    at /home/pankaj/projects/requests-service/test/create.js:127:31
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
  message: 'expected 45 to deeply equal 5',
  showDiff: true,
  actual: 45,
  expected: 5 }
    ✓ should create a shoutout (486ms)

  1 passing (1s)

 What could possibly be the reason for this behavior?

Thanks

**Comment by mpuittinen** [comment]
Merged and included in package 1.10.0
