### ISSUE TITLE
Create TypeScript function/test templates

### ISSUE THREAD

**Issue by evergreen-lee-campbell** [nordcloud/serverless-mocha-plugin#94]
It'd be great to pass a flag during `sls create function ...` that denotes that the created function/test pair should be in TypeScript, or detect the presence of `serverless-plugin-typescript` and create functions/tests in TypeScript by default, if present.

**Comment by mulib** [comment]
i could not make it work with typescript...getting error:
Serverless: No tests to run
can i get snippet for how to run .ts test file?
