### ISSUE TITLE
mochaPlugin.getWrapper and related documentation

### ISSUE THREAD

**Issue by yogabbagabb** [nordcloud/serverless-mocha-plugin#97]
I was following [this nice guide to test-driven development](https://serverless.com/blog/tdd-serverless/)

At some point, we are instructed to use `sls create test -f functionName.js`, which creates a file `functionName.js` with something similar to the following:

```javascript
'use strict';

// tests for functionName
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('functionName', '/handler.js', 'handler');

describe('functionName', () => {
  before((done) => {
    done();
  });

  it('implement tests here', () => {
    return wrapped.run({}).then((response) => {
      expect(response).to.not.be.empty;
    });
  });
});
```

I don't know what `mochaPlugin.getWrapper` does, and there is no documentation for this function. What does `mochaPlugin.getWrapper` do? If I want to know what other functionality `mochaPlugin` has, what should do I to learn it? Are there docs for serverless-mocha-plugin?
________

 I apologize if I'm overlooking an already-published set of docs for `mochaPlugin` -- I just can't find it, in that case.

**Comment by edipetres** [comment]
I cannot find it either. I've been looking for an hour now but nowhere seems to be documented. I wonder why any self-respecting developer would publish that without documentation (that *can* be found).
